/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_freerdp_services_LibFreeRDP */

#ifndef _Included_com_freerdp_services_LibFreeRDP
#define _Included_com_freerdp_services_LibFreeRDP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_freerdp_services_LibFreeRDP
 * Method:    freerdp_init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_freerdp_services_LibFreeRDP_freerdp_1init
  (JNIEnv *, jclass);

/*
 * Class:     com_freerdp_services_LibFreeRDP
 * Method:    freerdp_login
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_freerdp_services_LibFreeRDP_freerdp_1login
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_freerdp_services_LibFreeRDP
 * Method:    freerdp_copy_bitmap
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_freerdp_services_LibFreeRDP_freerdp_1copy_1bitmap
  (JNIEnv *, jclass);

/*
 * Class:     com_freerdp_services_LibFreeRDP
 * Method:    freerdp_send_cursor_event
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_freerdp_services_LibFreeRDP_freerdp_1send_1cursor_1event
  (JNIEnv *, jclass);

/*
 * Class:     com_freerdp_services_LibFreeRDP
 * Method:    freerdp_send_key_event
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_freerdp_services_LibFreeRDP_freerdp_1send_1key_1event
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
