/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_demo_DemoApplication */

#ifndef _Included_com_example_demo_DemoApplication
#define _Included_com_example_demo_DemoApplication
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_demo_DemoApplication
 * Method:    login
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_demo_DemoApplication_login
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
